### ISSUE TITLE
Tag releases please

### ISSUE THREAD

**Issue by stuart-c-moore** [frodenas/gcs-resource#11]
Hi,

Can you please consider tagging releases made to this gcs-resource? This would allow us to easily test changes made to this resource without risking breaking all of our production pipelines.

Thanks ...

**Comment by dazjones** [comment]
I would also like to request this.

Thanks

**Comment by frodenas** [comment]
Looks reasonable, but please remember that you will need to add the tag to the docker image at the resource type, and although it's a good practice, I've seen few people doing this.

**Comment by cagiti** [comment]
Yes, supporting this request it would be nice to have a tag filter on the concourse/docker-image-resource. That way it would entice people to filter on versions. _I should go and create a pull request_

**Comment by frodenas** [comment]
Done. Available docker image tags are:

* `master` will contain the latest changes to the master branch
* `v*.*.*` will contain specific release/tag versions
* `latest` will contain the latest `v*.*.*` release

See [frodenas/gcs-resource](https://hub.docker.com/r/frodenas/gcs-resource/tags/) tags at docker hub.
