### ISSUE TITLE
[feature request] Option for CacheControl

### ISSUE THREAD

**Issue by belljustin** [frodenas/gcs-resource#27]
[GCS defaults to caching public objects for 3600 secs](https://github.com/googleapis/google-api-go-client/blob/master/storage/v1/storage-gen.go#L1425-L1428). This resulted in requests for an object returning a stale object when I was expecting the latest one.

This could be changed by adding a cacheControl argument to [UploadFile](https://github.com/frodenas/gcs-resource/blob/master/gcsclient.go#L22) and passing it to the [storage Object](https://github.com/frodenas/gcs-resource/blob/master/gcsclient.go#L159-L162).

If there's interest in this feature, I'd be happy to take a crack at adding it.

**Comment by frodenas** [comment]
Sounds good, your contribution will be really appreciated.
