### ISSUE TITLE
`skip_download` param in the implicit get when put

### ISSUE THREAD

**Issue by guiguan** [frodenas/gcs-resource#30]
When put a large object to `gcs`, it is a kind of waste to download the object again from the bucket because of the implicit `get`. Can we provide a param, e.g. `skip_download`, to skip downloading the file, and just retrieve its metadata, e.g. generation and url?

**Comment by jmccann** [comment]
Seems this would be fixed by https://github.com/frodenas/gcs-resource/pull/36

**Comment by frodenas** [comment]
Fixed at #36.
