### ISSUE TITLE
Version 0.5.0 failed with "No such file or directory

### ISSUE THREAD

**Issue by cdutra** [frodenas/gcs-resource#33]
Hi,

we just noticed our gcs resources using latest (0.5.0) started failing on the checks with the following output:
```
Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:345: starting container process caused \"no such file or directory\"\n","Handle":"","ProcessID":"","Binary":""}
```

Thanks,

cc @davewalter

**Comment by goutamtadi1** [comment]
+2

**Comment by frodenas** [comment]
I've reverted https://github.com/frodenas/gcs-resource/commit/39e9a5566fd53383abe1009c6e7da4c6a6e97ba6 (#32).  The docker image with the `latest` tag is now using busybox again.
