### ISSUE TITLE
error running command: stream error: stream ID 5; INTERNAL_ERROR

### ISSUE THREAD

**Issue by syslxg** [frodenas/gcs-resource#37]
we have seen this error a few times in our pipeline while downloading files from GCP. It worked after re-trigger the builds. I can find a similar issue in  https://github.com/googleapis/google-cloud-go/commits/987caa2d3895c188c40784ad94fe1dd681a8cf68, which is fixed by https://github.com/googleapis/google-cloud-go/commits/d19004dbb.

But this resource is using a deprecated pkg `google.golang.org/api/storage/v1`. and the new one `cloud.google.com/go/storage` is not backward compatible. so we wont't get the same fix by bumping the pkg.

Any chance switching to `cloud.google.com/go/storage`?

**Comment by frodenas** [comment]
@syslxg I don't have the bandwidth to update the google libraries, but I'm open to a contribution :)
