### ISSUE TITLE
skip_download on a get question..

### ISSUE THREAD

**Issue by eitansuez** [frodenas/gcs-resource#41]
hi, this is not so much an issue as it is a question.
trying to make sense of what i'm seeing.
i've been trying to use skip_download on a get as documented and it never seemed to work.
is this new release version 0.6 the first release to enable this feature?
why is the field of type string?
thanks in advance. / eitan

**Comment by frodenas** [comment]
Yes, 0.6 is the first version enabling this feature.

**Comment by eitansuez** [comment]
thanks.
